# Checkov Configuration
# Skip checks that are acceptable for this use case

# Skip checks with reasons:
# CKV_TF_1: Module sources without commit hash - Using semantic versioning (~> 5.0) is standard practice
# CKV_AWS_338: CloudWatch log retention < 1 year - 1 year retention may be excessive for dev/demo environment  
# CKV_DOCKER_2: Missing HEALTHCHECK in Dockerfile - ECS has its own health check mechanism defined in task definition
# CKV_DOCKER_3: No non-root user in container - nginx:alpine runs as nginx user by default after startup
# CKV_AWS_150: ALB deletion protection - Not needed for dev/demo environment
# CKV_AWS_2: ALB HTTPS protocol - Using HTTP for dev/demo, HTTPS would require certificates
# CKV_AWS_111: IAM write access constraints - These are in external modules, not actionable
# CKV_AWS_356: IAM wildcard resources - These are in external modules, not actionable
# CKV_AWS_97: EFS encryption in transit - Not using EFS volumes
# CKV_AWS_300: S3 lifecycle abort period - These are in external modules, not actionable
skip-check:
  - CKV_TF_1
  - CKV_AWS_338
  - CKV_DOCKER_2
  - CKV_DOCKER_3
  - CKV_AWS_150
  - CKV_AWS_2
  - CKV_AWS_111
  - CKV_AWS_356
  - CKV_AWS_97
  - CKV_AWS_300

# Framework configurations
framework:
  - terraform
  - dockerfile
  - github_actions

# Output configuration
output: cli
compact: true

# Severity thresholds
soft-fail: false
