name: Checkov Security Scan

on:
  pull_request:
    paths:
      - '**.tf'
      - '**.py'
      - '**.sh'
      - '**/Dockerfile'

permissions:
  contents: read
  pull-requests: read
  security-events: write

jobs:
  checkov:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          config_file: .checkov.yaml
          framework: terraform,dockerfile,github_actions
          output_format: sarif
          output_file_path: checkov.sarif
          soft_fail: false
          quiet: true
          compact: true
          download_external_modules: true

      - name: Upload Checkov SARIF results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov.sarif
